<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil kategori yang ada
        $categories = Category::all();

        if ($categories->isEmpty()) {
            $this->command->warn('Tidak ada kategori ditemukan. Jalankan CategorySeeder terlebih dahulu.');
            return;
        }

        // Mapping genre ke category slug
        $genreToCategory = [
            'romance' => $categories->where('slug', 'romance')->first()?->id ?? $categories->first()->id,
            'drama' => $categories->where('slug', 'drama')->first()?->id ?? $categories->first()->id,
            'fiksi-remaja' => $categories->where('slug', 'fiksi-remaja')->first()?->id ?? $categories->first()->id,
            'fantasi' => $categories->where('slug', 'fantasi')->first()?->id ?? $categories->first()->id,
            'horor-fantasi' => $categories->where('slug', 'horor-fantasi')->first()?->id ?? $categories->first()->id,
            'politik' => $categories->where('slug', 'politik')->first()?->id ?? $categories->first()->id,
            'agama' => $categories->where('slug', 'agama')->first()?->id ?? $categories->first()->id,
            'inspiratif' => $categories->where('slug', 'inspiratif')->first()?->id ?? $categories->first()->id,
        ];

        $products = [
            // === ROMANCE ===
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Twisted Love',
                'slug' => 'twisted-love',
                'description' => 'Kisah cinta penuh konflik antara Ava dan Alex Volkov, pria dingin dengan masa lalu kelam.',
                'price' => 55000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book2.jpeg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Tentang Kamu',
                'slug' => 'tentang-kamu',
                'description' => 'Kisah pencarian kebenaran tentang kehidupan seorang perempuan bernama Sri Ningsih.',
                'price' => 48000,
                'discount_price' => 42000,
                'stock' => 35,
                'weight' => 320,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book5.jpeg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Fabricante De La Grimas',
                'slug' => 'fabricante-de-la-grimas',
                'description' => 'Kisah emosional tentang Nica dan Rigel yang penuh misteri.',
                'price' => 40000,
                'discount_price' => null,
                'stock' => 40,
                'weight' => 300,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book16.jpeg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Boulevard',
                'slug' => 'boulevard',
                'description' => 'Kisah cinta pahit-manis antara Hasley dan Luke.',
                'price' => 58000,
                'discount_price' => 50000,
                'stock' => 45,
                'weight' => 340,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'books/book17.jpeg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Kita & Waktu',
                'slug' => 'kita-waktu',
                'description' => 'Kisah tentang cinta, waktu, dan perpisahan.',
                'price' => 52000,
                'discount_price' => null,
                'stock' => 30,
                'weight' => 310,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book18.jpeg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Five Feet Apart',
                'slug' => 'five-feet-apart',
                'description' => 'Kisah cinta Stella dan Will yang berjuang melawan cystic fibrosis.',
                'price' => 45000,
                'discount_price' => null,
                'stock' => 55,
                'weight' => 290,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book15.jpeg',
            ],

            // === DRAMA ===
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Bandung After Rain',
                'slug' => 'bandung-after-rain',
                'description' => 'Kisah cinta dan kenangan di Kota Bandung yang romantis.',
                'price' => 47000,
                'discount_price' => null,
                'stock' => 40,
                'weight' => 300,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book19.jpeg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Van Der Wijick',
                'slug' => 'van-der-wijick',
                'description' => 'Kisah cinta tragis Zainuddin dan Hayati yang mengharukan.',
                'price' => 65000,
                'discount_price' => 55000,
                'stock' => 25,
                'weight' => 380,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book20.jpeg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Dilan 1990',
                'slug' => 'dilan-1990',
                'description' => 'Kisah cinta unik antara Dilan dan Milea yang ikonik.',
                'price' => 45000,
                'discount_price' => null,
                'stock' => 100,
                'weight' => 280,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book24.jpeg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Echoes In The Dark',
                'slug' => 'echoes-in-the-dark',
                'description' => 'Kisah emosional tentang cinta dan rahasia kelam.',
                'price' => 50000,
                'discount_price' => 42000,
                'stock' => 35,
                'weight' => 320,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'books/book25.jpeg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Selamat Tinggal',
                'slug' => 'selamat-tinggal',
                'description' => 'Kisah tentang Sikandar dan kerasnya dunia yang mengajarkan tentang kehidupan.',
                'price' => 48000,
                'discount_price' => null,
                'stock' => 30,
                'weight' => 310,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book11.jpeg',
            ],

            // === FIKSI REMAJA ===
            [
                'category_id' => $genreToCategory['fiksi-remaja'],
                'name' => 'they both die at the end',
                'slug' => 'they-both-die-at-the-end',
                'description' => 'Dua remaja, Mateo dan Rufus, bertemu di hari terakhir hidup mereka.',
                'price' => 60000,
                'discount_price' => 50000,
                'stock' => 45,
                'weight' => 340,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book3.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fiksi-remaja'],
                'name' => 'Shadow Gril',
                'slug' => 'shadow-gril',
                'description' => 'Kisah cinta gelap dan emosional tentang gadis pendiam dengan masa lalu kelam.',
                'price' => 52000,
                'discount_price' => null,
                'stock' => 38,
                'weight' => 300,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book4.jpeg',
            ],

            // === FANTASI ===
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Bumi',
                'slug' => 'bumi',
                'description' => 'Awal petualangan Raib di dunia paralel yang menakjubkan.',
                'price' => 60000,
                'discount_price' => null,
                'stock' => 60,
                'weight' => 380,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book12.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Bulan',
                'slug' => 'bulan',
                'description' => 'Lanjutan kisah Raib, Seli, dan Ali di Klan Bulan yang misterius.',
                'price' => 70000,
                'discount_price' => 60000,
                'stock' => 50,
                'weight' => 400,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book13.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Matahari',
                'slug' => 'matahari',
                'description' => 'Petualangan Raib, Seli, dan Ali di dunia paralel Klan Matahari.',
                'price' => 65000,
                'discount_price' => null,
                'stock' => 55,
                'weight' => 390,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book6.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Bintang',
                'slug' => 'bintang',
                'description' => 'Petualangan Raib, Seli, dan Ali di Klan Bintang yang memukau.',
                'price' => 55000,
                'discount_price' => 48000,
                'stock' => 48,
                'weight' => 360,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book10.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Harry Potter',
                'slug' => 'harry-potter',
                'description' => 'Kisah Harry Potter di Hogwarts yang legendaris.',
                'price' => 42000,
                'discount_price' => null,
                'stock' => 120,
                'weight' => 450,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book14.jpeg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Kesatria, Putri, & Bintang Jatuh',
                'slug' => 'kesatria-putri-bintang-jatuh',
                'description' => 'Kumpulan cerita dongeng modern yang memukau.',
                'price' => 52000,
                'discount_price' => null,
                'stock' => 42,
                'weight' => 330,
                'is_active' => true,
                'is_featured' => false,
                'image' => 'books/book23.jpeg',
            ],

            // === HOROR FANTASI ===
            [
                'category_id' => $genreToCategory['horor-fantasi'],
                'name' => 'Night Books',
                'slug' => 'night-books',
                'description' => 'Novel horor fantasi tentang Alex yang dipaksa menceritakan kisah seram setiap malam.',
                'price' => 45000,
                'discount_price' => null,
                'stock' => 35,
                'weight' => 290,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book1.jpeg',
            ],

            // === POLITIK ===
            [
                'category_id' => $genreToCategory['politik'],
                'name' => 'Negeri Para Bedebah',
                'slug' => 'negeri-para-bedebah',
                'description' => 'Kisah penuh intrik tentang Thomas dan konspirasi besar di negeri ini.',
                'price' => 58000,
                'discount_price' => 50000,
                'stock' => 28,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book7.jpeg',
            ],
            [
                'category_id' => $genreToCategory['politik'],
                'name' => 'Hujan',
                'slug' => 'hujan',
                'description' => 'Kisah cinta dan kehilangan Lail dan Esok di masa depan yang suram.',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 40,
                'weight' => 310,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book9.jpeg',
            ],

            // === AGAMA ===
            [
                'category_id' => $genreToCategory['agama'],
                'name' => 'Kau, Aku dan Sepucuk Angpau Merah',
                'slug' => 'kau-aku-sepucuk-angpau-merah',
                'description' => 'Kisah sederhana tentang persahabatan, cinta, dan keikhlasan.',
                'price' => 62000,
                'discount_price' => null,
                'stock' => 32,
                'weight' => 320,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book8.jpeg',
            ],

            // === INSPIRATIF ===
            [
                'category_id' => $genreToCategory['inspiratif'],
                'name' => 'Ranah 3 Warna',
                'slug' => 'ranah-3-warna',
                'description' => 'Perjalanan Alif Fikri mengejar mimpi di perantauan.',
                'price' => 55000,
                'discount_price' => 48000,
                'stock' => 50,
                'weight' => 360,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book21.jpeg',
            ],
            [
                'category_id' => $genreToCategory['inspiratif'],
                'name' => 'Rantau 1 Muara',
                'slug' => 'rantau-1-muara',
                'description' => 'Penutup kisah Alif Fikri di perantauan yang menginspirasi.',
                'price' => 48000,
                'discount_price' => null,
                'stock' => 45,
                'weight' => 340,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book22.jpeg',
            ],
            // New books from book26 to book50
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Binding',
                'slug' => 'binding',
                'description' => 'Binding-Chloe Walsh – Cerita emosional tentang trauma, ikatan batin, dan perjuangan menerima cinta di tengah luka dalam. 🖤🤍',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book26.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Aprendiz del Villano',
                'slug' => 'aprendiz-del-villano',
                'description' => 'Aprendiz del Villano-Hannah Nicole Maehrer – Kisah fantasi gelap tentang seorang murid yang belajar dari penjahat legendaris, di antara humor, bahaya, dan dilema moral. 😈📘',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book27.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Twisted Lies',
                'slug' => 'twisted-lies',
                'description' => 'Twisted Lies-Ana Huang – Romansa penuh intrik antara kebohongan, kekuasaan, dan cinta yang tumbuh di atas rahasia berbahaya. 🕶️❤️',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book28.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Twisted Hate',
                'slug' => 'twisted-hate',
                'description' => 'Twisted Hate-Ana Huang – Cerita enemies-to-lovers yang penuh emosi, konflik panas, dan ketertarikan yang sulit dihindari. 🔥💢',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book29.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Twisted Games',
                'slug' => 'twisted-games',
                'description' => 'Twisted Games-Ana Huang – Romansa kerajaan modern tentang kewajiban, cinta terlarang, dan pilihan antara hati atau tahta. 👑💔',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book30.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'The Sweetest Oblivion',
                'slug' => 'the-sweetest-oblivion',
                'description' => 'The Sweetest Oblivion-Danielle Lori – Kisah cinta mafia yang intens, berbahaya, dan penuh ketegangan antara gairah dan kesetiaan. 🖤🔫',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book31.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Hooked',
                'slug' => 'hooked',
                'description' => 'Hooked-Emily McIntire – Interpretasi gelap romansa tentang obsesi, balas dendam, dan cinta yang tak sehat namun memikat. 🪝🖤',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book32.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Crossed',
                'slug' => 'crossed',
                'description' => 'Crossed-Emily McIntire – Cerita penuh konflik batin tentang pilihan moral, pengkhianatan, dan cinta di sisi tergelap manusia. ⚔️❤️',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book33.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Scarred',
                'slug' => 'scarred',
                'description' => 'Scarred-Emily McIntire – Novel ini mengeksplorasi luka emosional dan fisik, serta cinta yang tumbuh dari trauma dan rasa sakit. 🩸💔',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book34.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Fourth Wing',
                'slug' => 'fourth-wing',
                'description' => 'Fourth Wing-Rebecca Yarros – Fantasi epik tentang akademi naga, peperangan, dan perjuangan seorang gadis bertahan di dunia mematikan. 🐉🔥',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book35.jpg',
            ],
            [
                'category_id' => $genreToCategory['horor-fantasi'],
                'name' => 'Asylum',
                'slug' => 'asylum',
                'description' => 'Asylum-Madeleine Roux – Kisah horor psikologis di sebuah rumah sakit jiwa terbengkalai, penuh rahasia dan teror masa lalu. 🏚️😱',
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book36.jpg',
            ],
            [
                'category_id' => $genreToCategory['horor-fantasi'],
                'name' => 'Hide and Don’t Seek',
                'slug' => 'hide-and-dont-seek',
                'description' => "Hide and Don't Seek-Anica Mrose Rissi – Thriller menegangkan tentang permainan berbahaya yang berubah menjadi mimpi buruk mematikan. 🕯️🔪",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book37.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Nevernight',
                'slug' => 'nevernight',
                'description' => "Nevernight-Jay Kristoff – Fantasi gelap tentang seorang gadis yang dilatih menjadi pembunuh demi membalas dendam pada dunia. 🌑🗡️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book38.jpg',
            ],
            [
                'category_id' => $genreToCategory['horor-fantasi'],
                'name' => 'Jack the Ripper',
                'slug' => 'jack-the-ripper',
                'description' => "Jack the Ripper-Kerri Maniscalco – Misteri sejarah tentang pembunuh legendaris London, dipadukan dengan kecerdasan dan ketegangan yang mencekam. 🔍🩸",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book39.jpg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Inherited',
                'slug' => 'inherited',
                'description' => "Inherited-Alex Grey – Thriller kriminal tentang warisan kelam yang menyeret tokohnya ke dalam kejahatan dan rahasia berbahaya. 🧬⚠️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book40.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Crimson Rogue Cheongfios',
                'slug' => 'crimson-rogue-cheongfios',
                'description' => "Crimson Rogue Cheongfios-Laselle – Kisah fantasi penuh intrik tentang pemberontakan, darah bangsawan, dan kekuatan terlarang. 🩸⚔️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book41.jpg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'The Death Pact',
                'slug' => 'the-death-pact',
                'description' => "The Death Pact-Susan Summers – Novel menegangkan tentang perjanjian berbahaya yang mengikat hidup dan kematian para tokohnya. ☠️📜",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book42.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Fire in the Sky',
                'slug' => 'fire-in-the-sky',
                'description' => "Fire in the Sky-Sophie Jordan – Cerita petualangan fantasi tentang kekuatan api, takdir, dan perjuangan melawan kekuasaan tirani. 🔥🌌",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book43.jpg',
            ],
            [
                'category_id' => $genreToCategory['romance'],
                'name' => 'Scarlet Huntress',
                'slug' => 'scarlet-huntress',
                'description' => "Scarlet Huntress-Leann Mason – Kisah seorang pemburu wanita yang terjebak antara kewajiban, cinta, dan rahasia dunia magis. 🏹❤️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book44.jpg',
            ],
            [
                'category_id' => $genreToCategory['drama'],
                'name' => 'Cold Lake',
                'slug' => 'cold-lake',
                'description' => "Cold Lake-Jeff Carson – Thriller kriminal berlatar kota kecil dengan kasus pembunuhan misterius dan rahasia gelap penduduknya. ❄️🔎",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book45.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Witch',
                'slug' => 'witch',
                'description' => "Witch-Finbar Hawkins – Cerita fantasi tentang penyihir muda yang harus memilih antara kekuatan dan kemanusiaannya. 🧙‍♀️✨",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book46.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'The Uncrowned Queen',
                'slug' => 'the-uncrowned-queen',
                'description' => "The Uncrowned Queen-Lucy Steele – Novel fantasi politik tentang perebutan tahta, pengkhianatan, dan seorang ratu tanpa mahkota. 👑⚔️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book47.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'The Sea Witch',
                'slug' => 'the-sea-witch',
                'description' => "The Sea Witch-Eva Leight – Kisah magis berlatar laut tentang penyihir, kutukan, dan cinta yang terlarang. 🌊🧜‍♀️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book48.jpg',
            ],
            [
                'category_id' => $genreToCategory['fantasi'],
                'name' => 'Of the Dark Moon',
                'slug' => 'of-the-dark-moon',
                'description' => "Of the Dark Moon-Melissa Kieran – Fantasi romantis tentang kekuatan bulan gelap, rahasia kuno, dan cinta di tengah kegelapan. 🌑💫",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book49.jpg',
            ],
            [
                'category_id' => $genreToCategory['fiksi-remaja'],
                'name' => 'Human',
                'slug' => 'human',
                'description' => "Human-Greassy Microwave – Novel distopia reflektif tentang arti menjadi manusia di dunia yang perlahan kehilangan empati. 🤖❤️",
                'price' => 50000,
                'discount_price' => null,
                'stock' => 50,
                'weight' => 350,
                'is_active' => true,
                'is_featured' => true,
                'image' => 'books/book50.jpg',
            ],
        ];

        foreach ($products as $productData) {
            // Extract image path before creating product
            $imagePath = $productData['image'] ?? 'products/placeholder.jpg';
            unset($productData['image']);
            
            $product = Product::updateOrCreate(
                ['slug' => $productData['slug']],
                $productData
            );

            // Update gambar produk
            \App\Models\ProductImage::updateOrCreate(
                ['product_id' => $product->id, 'is_primary' => true],
                [
                    'image_path' => $imagePath,
                    'sort_order' => 1,
                ]
            );
        }

        $this->command->info('Berhasil membuat ' . count($products) . ' produk buku dengan gambar yang benar.');
    }
}
